env:
  es6: true
 
plugins: [
  "fp"
]

parser: 
  "babel-eslint"
  
rules:
  max-lines:
  - warn
  - 200

  max-lines-per-function:
  - warn
  - 100

  complexity:
  - warn
  - 5
  
  max-nested-callbacks:
  - warn
  - 3

  max-depth:
  - warn
  - 4

  max-params:
  - warn
  - 3
  
  no-param-reassign: warn
  fp/no-this: warn
  fp/no-mutating-assign: warn
  fp/no-mutating-methods: warn
  fp/no-delete: warn
  fp/no-throw: warn

  eqeqeq: warn
  no-eq-null: warn
  no-empty-function: warn
  no-empty-pattern: warn
  no-fallthrough: warn
  no-lone-blocks: warn
  no-multi-spaces: warn
  no-new-wrappers: warn
  no-redeclare: warn
  no-return-assign: warn
  no-useless-catch: warn
  no-useless-escape: warn
  no-useless-return: warn
  require-await: warn
  no-undefined: warn
  no-console: warn
  no-unused-vars: warn
